services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - USE_REAL_MODEL=true
      - LOCAL_MODEL=google/flan-t5-small
      - HF_MODEL=google/flan-t5-small
    volumes:
      - hf_cache:/root/.cache/huggingface
      - ./backend/app:/app/app:ro
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  hf_cache:
